# -*- coding: utf-8 -*-
"""kofam_to_mpp_format_conversion

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EhT5W0Pu_inJFN_exdYa93IsTG4CywGH
"""

# Read the original lines from the uploaded file
with open('Ecoli_kofamscan_output.txt', 'r') as file:
    original_lines = file.readlines()

header_line_1 = "#\tgene_name\tKO\tthreshold\tscore\tE-value\tKO_definition\n"
header_line_2 = "#\t---------\t------\t-------\t------\t---------\t-------------\n"
output_content = [header_line_1, header_line_2]

for line in original_lines[2:]:
    parts = line.strip().split(maxsplit=5)

    # Assume the last part is the KO definition and may contain multiple columns
    parts[-1] = parts[-1].replace(' ', '\t', 1)  # Replace the first space with underscore to maintain two columns only
    # Join the parts back with a tab separator and add a newline
    output_line = '\t'.join(parts) + '\n'
    # Append the processed line to the output content
    output_content.append(output_line)

# Write the output content to a TSV file
output_file_path_final = 'Ecoli_kofamscan_output.tsv'
with open(output_file_path_final, 'w') as file:
    file.writelines(output_content)

output_file_path_final

